# Generated by Django 5.2 on 2025-05-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_groups_user_user_permissions_alter_user_email_and_more",
        ),
        ("accounts", "0003_drop_username"),
    ]

    operations = []
