# Generated by Django XYZ on 2025-05-26 ABCD

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20250526_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                'email address',
                unique=True,
                max_length=254
            ),
        ),
    ]
